name: lewd
version: 1.0.0
synopsis: Quick-and-dirty base replacement
description: Monolithic drop-in replacement for base to kick-start common productive workflows
maintainer: goverthrow <goverthrow@protonmail.com>
github: goverthrow/lewd
category: Prelude
license: PublicDomain

dependencies:
  - base >= 4.7 && <= 5

  - bytestring
  - async
  - file-embed
  - directory
  - filepath
  - process
  - text
  - text-show
  - containers
  - unordered-containers
  - mtl
  - lens
  - stm
  - random
  - double-conversion
  - data-default
  - aeson
  - uri-encode
  - random-shuffle
  - conduit
  - conduit-extra

  - websockets
  - warp
  - wai
  - wai-extra
  - wai-websockets
  - http-types
  - warp-tls
  - wuss
  - http-conduit

  - mongoDB
  - bson

  # - gloss
  # - gloss-algorithms


# ghc-options: !include ../common/opts.yaml
default-extensions: !include ../common/exts.yaml

library:
  source-dirs: src
  reexported-modules: !include base.yaml
